services:
  backend:
    build: ./wyr-backend
    container_name: qr_attendance_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: qr_attendance_db
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-scripts/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

volumes:
  pgdata:
